Add a logo to top
3kh0/3kh0.github.io pull request #137
Opened 2022-10-18 15:32 UTC by nicolasog12

Add logo to top of webpage - testing

2022-10-18 15:34 UTC, nicolasog12 commented
I'm testing it and checking for bugs once it deploys to vercel

2022-10-18 15:36 UTC, nicolasog12 commented
Ok i found a bug

2022-10-18 15:49 UTC, nicolasog12 commented
11:48 est - still wating

2022-10-18 15:52 UTC, 3kh0 reviewed
It might be a good idea to replace the main text `3kh0.github.io` with the image, see how that looks. See if you can get rid of the black lines as well

![image](https://user-images.githubusercontent.com/58097612/196480746-104839a6-1d32-4cbc-b687-3778d78d6bda.png)

2022-10-18 15:52 UTC, 3kh0 commented on css/index.css
> +  border-bottom: 1px solid black;
Make this 0px to hide the border

2022-10-18 15:52 UTC, 3kh0 commented on css/projects.css
> +  border-bottom: 1px solid black;
Make this 0px to hide the border

2022-10-18 15:58 UTC, nicolasog12 commented
_preparing for reviews..._

2022-10-18 16:14 UTC, nicolasog12 commented on css/projects.css
> +  border-bottom: 1px solid black;
ok

2022-10-18 17:03 UTC, 3kh0 reviewed
It might be a good idea to replace the main text 3kh0.github.io with the image, see how that looks.

2022-10-18 17:06 UTC, nicolasog12 commented
> It might be a good idea to replace the main text 3kh0.github.io with the image, see how that looks.

alright workin on it

2022-10-18 17:10 UTC, nicolasog12 commented
done, waiting for vercel deployment.

2022-10-18 17:16 UTC, nicolasog12 commented
waiting for deploy

2022-10-18 17:19 UTC, nicolasog12 commented
ok theres still a bug

2022-10-18 17:27 UTC, nicolasog12 commented
Im getting an annoying not centering bug, im just gonna keep tryna fix it

2022-10-18 17:41 UTC, nicolasog12 commented
Ok so I've tried everything I can to fix it and it's obviously either my bad coding or the thing (probably the first one) so I just made the title font Raleway and the color gold, so it look similar.

2022-10-19 00:30 UTC, 3kh0 requested changes
![image](https://user-images.githubusercontent.com/58097612/196569587-fb351bd6-0069-4d25-8034-7a783175586b.png)

remove the logo on the top, add the logo to the 3kh0.github.io text bit right above the splash text

2022-10-19 12:25 UTC, nicolasog12 commented
> ![image](https://user-images.githubusercontent.com/58097612/196569587-fb351bd6-0069-4d25-8034-7a783175586b.png)
> 
> remove the logo on the top, add the logo to the 3kh0.github.io text bit right above the splash text

so just replace the title text with the logo image

2022-10-19 13:24 UTC, 3kh0 commented
yes

2022-10-19 13:32 UTC, nicolasog12 commented
ill work on it

2022-10-19 13:59 UTC, nicolasog12 commented
btw if you wanted to know the website that made the logo its just
https://brandmark.io

2022-10-19 15:49 UTC, nicolasog12 commented
where is the vercel deploy???

2022-10-19 20:07 UTC, 3kh0 requested changes
Please add spacing on the top

![image](https://user-images.githubusercontent.com/58097612/196793290-d771776a-df45-4119-a52d-0cbd309081b4.png)

2022-10-19 20:07 UTC, 3kh0 commented on index.html
> -    </h1>
Put the image within the `<h1>` tag

2022-10-19 21:47 UTC, nicolasog12 commented on index.html
> -    </h1>
alright

2022-10-20 13:13 UTC, 3kh0 requested changes
The logo at the top needs some padding from the top, and the splash text needs to be centered

2022-10-20 15:59 UTC, nicolasog12 commented
> The logo at the top needs some padding from the top, and the splash text needs to be centered

The splash text is centered in the css, I can't figure out why its not working

2022-10-20 16:00 UTC, closed without merging